[package]
name = "rust-echo-server"
version = "0.0.1"
authors = ["Anish Dhanka <anish.mourya5@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "~0.13.4"
tokio = { version = "0.2", features = ["full"] }
pretty_env_logger = "0.4"
futures = "0.3.0"
